### ISSUE TITLE
ToJSON type error

### ISSUE THREAD

**Issue by luoqeng** [cozy/prosemirror-go#1]
prosemirror-transform toJSON stepType https://github.com/ProseMirror/prosemirror-transform/blob/master/src/replace_step.js#L61

prosemirror-go ToJSON type https://github.com/cozy/prosemirror-go/blob/master/transform/replace_step.go#L95

**Comment by nono** [comment]
Thanks, it has been fixed with https://github.com/cozy/prosemirror-go/commit/d2592e2aca7bd014a2020566081a8150a4a35143
