### ISSUE TITLE
transform map error

### ISSUE THREAD

**Issue by luoqeng** [cozy/prosemirror-go#2]
https://github.com/cozy/prosemirror-go/blob/master/transform/map.go#L102
```
var side int
if oldSize == 0 {
	side = assoc
} else if pos == start {
	side = 1
} else if pos == end {
	side = -1
} else {
	side = assoc
}
```

https://github.com/ProseMirror/prosemirror-transform/blob/master/src/map.js#L84
```
let side = !oldSize ? assoc : pos == start ? -1 : pos == end ? 1 : assoc
```

go `if pos == start side = 1`  
js `pos == start ? -1`

go `if pos == end side = -1` 
js ` pos == end ? 1`

**Comment by nono** [comment]
Thanks, it has been fixed by https://github.com/cozy/prosemirror-go/commit/42d8d32c24f46bd32bd627597d895802d2d33110
