### ISSUE TITLE
textBetween err

### ISSUE THREAD

**Issue by luoqeng** [cozy/prosemirror-go#3]
https://github.com/ProseMirror/prosemirror-model/blob/b7aa9df5a4c629bc6dbe0302c0661b204bc989fa/src/fragment.js#L49
https://github.com/cozy/prosemirror-go/blob/master/model/fragment.go#L93

should be
```
blockSeparator == ""
```

**Comment by nono** [comment]
Thanks a lot for finding those errors! It has been fixed with https://github.com/cozy/prosemirror-go/commit/8a38db5ce81e0ae6529f617649f298ae7cffb513
